apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "peopleapi-challenge-hs.fullname" . }}-db
spec:
  selector:
    matchLabels:
      app: {{ include "peopleapi-challenge-hs.fullname" . }}-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ include "peopleapi-challenge-hs.fullname" . }}-db
    spec:
      containers:
      - image: "{{ .Values.mariadb.repository }}:{{ .Values.mariadb.tag | default .Chart.AppVersion }}"
        name: {{ include "peopleapi-challenge-hs.fullname" . }}-db
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: mariadbcredentials
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: mariadbcredentials
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: MYSQL_DATABASE
              name: mariadbcredentials
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: mariadbcredentials
        ports:
        - containerPort: 3306
          name: mysql
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec mysqladmin status -uroot -p$MYSQL_ROOT_PASSWORD
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec mysqladmin status -uroot -p$MYSQL_ROOT_PASSWORD
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
            {{- toYaml .Values.resources_db | nindent 12 }}


